services:
  - type: web
    name: laravel-app
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: mysql
          name: fahim
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromService:
          type: mysql
          name: fahim
          property: database
      - key: DB_USERNAME
        fromService:
          type: mysql
          name: fahim
          property: user
      - key: DB_PASSWORD
        fromService:
          type: mysql
          name: fahim
          property: password

databases:
  - name: fahim
    plan: free
    mysqlVersion: 8
